---
apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: plex
  labels:
    app: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
  - name: http
    protocol: TCP
    port: 32400
    nodePort: 32400
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: plex
  namespace: plex
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      containers:
      - name: plex
        image: plexinc/pms-docker:1.12.0.4829-6de959918
        #imagePullPolicy: Always
        resources:
          requests:
            cpu: 1
            memory: 1024Mi
        readinessProbe:
          exec:
            command:
            - /healthcheck.sh
          failureThreshold: 5
          timeoutSeconds: 15
          periodSeconds: 15
        livenessProbe:
          exec:
            command:
            - /healthcheck.sh
          initialDelaySeconds: 120
          failureThreshold: 5
          timeoutSeconds: 15
          periodSeconds: 15
        ports:
        - containerPort: 32400
          name: http
        env:
        - name: TZ
          value: Europe/London
        - name: PUID
          value: "1000"
        - name: PGID
          value: "1000"
        volumeMounts:
        - name: data
          mountPath: /data
        - name: config
          mountPath: /config
        - name: transcode
          mountPath: /transcode
        - name: tmp
          mountPath: /tmp
      nodeName: node1.lukeaddison.co.uk
      volumes:
      - name: data
        nfs:
          server: node1.lukeaddison.co.uk
          path: "/mnt/data/plex"
          readOnly: true
      #- name: plex-config
      #  persistentVolumeClaim:
      #    claimName: plex
      - name: config
        hostPath:
          path: /srv/nfs/plex-plex-pvc-e4a59cb1-f3db-11e7-a397-7085c2230fb3
      - name: transcode
        emptyDir: {}
      - name: tmp
        emptyDir: {}
