---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  namespace: bookstack
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  tls:
  - secretName: bookstack-tls
    hosts:
    - wiki.lukeaddison.co.uk
  rules:
  - host: wiki.lukeaddison.co.uk
    http:
      paths:
      - backend:
          serviceName: bookstack
          servicePort: 80
